In [1]:
import numpy as np

In [2]:
n=3000
n_step=30

s1 = np.sin(np.pi * 0.06 * np.arange(n)) + np.random.random(n)
s2 = 0.5 * np.sin(np.pi * 0.05 * np.arange(n)) + np.random.random(n)

data = np.vstack([s1,s2]).T
data

array([[2.48265555e-01, 6.95696006e-01],
       [8.58915837e-01, 1.72091499e-01],
       [1.20876923e+00, 4.21175886e-01],
       ...,
       [3.32695841e-01, 4.41379479e-01],
       [9.81016135e-04, 6.22362006e-01],
       [5.21212619e-01, 1.72592538e-01]])

In [4]:
m = np.arange(0, n-n_step)

array([   0,    1,    2, ..., 2967, 2968, 2969])

In [8]:
x_train = np.array([data[i: (i+n_step),:] for i in m])
x_train.shape

(2970, 30, 2)

In [9]:
y_train = np.array([data[i,:] for i in (m+n_step)]) 
y_train

array([[-0.29778346,  0.47079532],
       [ 0.09796819,  0.39870415],
       [ 0.04746506,  0.4265682 ],
       ...,
       [ 0.33269584,  0.44137948],
       [ 0.00098102,  0.62236201],
       [ 0.52121262,  0.17259254]])

In [10]:
y_train.shape

(2970, 2)